const scheduledList = 
  [
    {
      ID: '1',
      Day: 'Monday',
      TimeIn: '7am',
      TimeOut: '10am',
      value: 7,
      Subject: 'Computer Programming 1, Lab',
      Teacher: 'Pasoc, Romer Ian',
    },
    {
      ID: '2',
      Day: 'Monday',
      TimeIn: '1pm',
      TimeOut: '2pm',
      value: 13,
      Subject: 'Purposive Communication',
      Teacher: 'TBA',
    },
    {
      ID: '3',
      Day: 'Monday',
      TimeIn: '3pm',
      TimeOut: '4pm',
      value: 15,
      Subject: 'Mathematics in the Modern World',
      Teacher: 'TBA',
    },
    {
      ID: '4',
      Day: 'Monday',
      TimeIn: '4pm',
      TimeOut: '5:30pm',
      value: 16,
      Subject: 'Understanding the Self',
      Teacher: 'TBA',
    },
    {
      ID: '5',
      Day: 'Tuesday',
      TimeIn: '8am',
      TimeOut: '9am',
      value: 8,
      Subject: 'Computer Programming 1',
      Teacher: 'Pasoc, Romer Ian',
    },
    {
      ID: '6',
      Day: 'Tuesday',
      TimeIn: '1pm',
      TimeOut: '2:30pm',
      value: 13,
      Subject: 'Ethics',
      Teacher: 'TBA',
    },
    {
      ID: '7',
      Day: 'Thursday',
      TimeIn: '8am',
      TimeOut: '9am',
      value: 8,
      Subject: 'Computer Programming 1',
      Teacher: 'Pasoc, Romer Ian',
    },
    {
      ID: '8',
      Day: 'Thursday',
      TimeIn: '11am',
      TimeOut: '1pm',
      value: 11,
      Subject: 'Introduction to Computing',
      Teacher: 'Bascones, Ferdinand Jr. D.',
    },
    {
      ID: '9',
      Day: 'Thursday',
      TimeIn: '1pm',
      TimeOut: '2:30pm',
      value: 13,
      Subject: 'Ethics',
      Teacher: 'TBA',
    },
    {
      ID: '10',
      Day: 'Wednesday',
      TimeIn: '1pm',
      TimeOut: '2pm',
      value: 13,
      Subject: 'Purposive Communication',
      Teacher: 'TBA',
    },
    {
      ID: '11',
      Day: 'Wednesday',
      TimeIn: '3pm',
      TimeOut: '4pm',
      value: 15,
      Subject: 'Mathematics in the Modern World',
      Teacher: 'TBA',
    },
    {
      ID: '12',
      Day: 'Friday',
      TimeIn: '7am',
      TimeOut: '9am',
      value: 7,
      Subject: 'Physical Activities Towards Health and Fitness I (PATH-Fit I): Movement Competency Training',
      Teacher: 'Cabahug, Dana Rica P.',
    },
    {
      ID: '13',
      Day: 'Friday',
      TimeIn: '10am',
      TimeOut: '1pm',
      value: 10,
      Subject: 'Introduction to Computing, Lab',
      Teacher: 'Bascones, Ferdinand Jr. D.',
    },
    {
      ID: '14',
      Day: 'Friday',
      TimeIn: '1pm',
      TimeOut: '2pm',
      value: 13,
      Subject: 'Purposive Communication',
      Teacher: 'TBA',
    },
    {
      ID: '15',
      Day: 'Friday',
      TimeIn: '3pm',
      TimeOut: '4pm',
      value: 15,
      Subject: 'Mathematics in the Modern World',
      Teacher: 'TBA',
    },
    {
      ID: '16',
      Day: 'Sunday',
      TimeIn: '8am',
      TimeOut: '12pm',
      value: 8,
      Subject: 'Reserved Officer Training Corps I',
      Teacher: 'TBA',
    }
  ];
export default scheduledList